spring:
  application:
    name: rbac-backend
  datasource:
    url: jdbc:mysql://localhost:3306/logistics_rbac_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: Spike
    password: 123dingdayi
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis mapper.xml路径配置
mybatis:
  mapper-locations:
    - classpath*:com/**/mapper/*.xml
    - classpath:dao/*.xml
server:
  port: 8088

logging:
  level:
    org.springframework: info
